version: "3"
services:
    api-gateway:
      image: traefik
      command: --api --web --docker --docker.domain=docker.localhost --docker.exposedbydefault=false --logLevel=INFO
      ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # Dashboard port
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    message-bus:
      image: 'rabbitmq:3-management'
      ports:
        - "5672"
        - 15672:15672
      networks:
        - default
    # onse-transaction-service
    transaction-service:
      build: ./onse-transaction-service
      restart: always
      ports:
        - "5000"
      volumes:
        - ./onse-transaction-service:/app
      depends_on:
        - message-bus
        - transaction-service-db
      environment:
        PORT: 5000
        RABBITMQ_PORT: 5672
        RABBITMQ_HOST: message-bus
        ACCOUNT_SERVICE_URL: "todo"
      networks:
        - default
    transaction-service-db:
      image: postgres:latest
      ports:
        - "5432"
      environment:
        POSTGRES_PASSWORD: guest
        POSTGRES_USER: guest
      networks:
        - default
    # onse-customer-service
    customer-service:
      build: ./onse-customer-service
      restart: always
      ports:
        - "5000"
      volumes:
        - ./onse-customer-service:/app
      environment:
        PORT: 5000
      networks:
        - default
      labels:
       - "traefik.enable=false"
       - "traefik.port=5000"
       - "traefik.backend=customer-service"
       - "traefik.frontend.rule=PathPrefix:/customers/"
    # onse-account-service
    account-service:
      build: ./onse-account-service
      restart: always
      ports:
        - "5000"
      volumes:
        - ./onse-account-service:/app
      environment:
        PORT: 5000
      networks:
        - default
      labels:
       - "traefik.enable=true"
       - "traefik.port=5000"
       - "traefik.backend=account-service"
       - "traefik.frontend.rule=PathPrefix:/account/"
    # onse-cashier-service
    cashier-service:
      build: ./onse-cashier-service
      restart: always
      ports:
        - "5000"
      volumes:
        - ./onse-cashier-service:/app
      environment:
        PORT: 5000
        RABBITMQ_PORT: 5672
        RABBITMQ_HOST: message-bus
        RABBITMQ_QUEUE: transactions
        RABBITMQ_EXCHANGE: transactions
      depends_on:
        - message-bus
      networks:
        - default
      labels:
       - "traefik.enable=true"
       - "traefik.port=5000"
       - "traefik.backend=cashier-service"
       - "traefik.frontend.rule=PathPrefix:/cashier/"

networks:
  default: