version: "3"
services:
    message-bus:
      image: 'rabbitmq:3-management'
      hostname: rabbitmq-host
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - default
    # onse-transaction-service
    transaction-service:
      build: ./onse-transaction-service
      restart: always
      volumes:
        - .:/app
      depends_on:
        - message-bus
        - transaction-service-db
      environment:
        RABBITMQ_PORT: 5672
        RABBITMQ_HOST: message-bus
        ACCOUNT_SERVICE_URL: "todo"
      networks:
        - default
    transaction-service-db:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: guest
        POSTGRES_USER: guest
      networks:
        - default
    # onse-customer-service
    customer-service:
      build: ./onse-customer-service
      restart: always
      volumes:
        - .:/app
      environment:
        PORT: 5000
      networks:
        - default
    # onse-account-service
    account-service:
      build: ./onse-customer-service
      restart: always
      volumes:
        - .:/app
      environment:
        PORT: 5000
      networks:
        - default


networks:
  default: